apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- cert-manager.yaml
resources:
- clusterissuers.yaml
patchesStrategicMerge:
- set-secrets.yaml
secretGenerator:
- envs:
  - secrets.env
  name: cert-manager-aws
  namespace: cert-manager
  type: Opaque
