apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- add-storage.yaml
resources:
- ../../upstream/kube-prometheus
- ingresses.yaml
- grafana-pvc.yaml
images:
- name: grafana/grafana
  newTag: 6.3.2
