apiVersion: platform.discogs.com/v1
kind: HelmChartGenerator
metadata:
  name: minio
spec:
  chart: stable/minio
  version: 2.5.16
  values:
    accessKey: $(envfile://secrets.env#ACCESS_KEY)
    secretKey: $(envfile://secrets.env#SECRET_KEY)
    image:
      tag: RELEASE.2019-10-12T01-39-57Z
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: public
        nginx.ingress.kubernetes.io/proxy-body-size: 32m
      enabled: true
      hosts:
      - obj.vreon.net
      tls:
      - hosts:
        - obj.vreon.net
        secretName: minio-tls
