apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../upstream/external-dns
- namespace.yaml
secretGenerator:
- envs:
  - secrets.env
  name: external-dns-aws
  type: Opaque
patchesStrategicMerge:
- set-secrets.yaml
- set-args.yaml
namespace: external-dns
