apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=ingress
        - --domain-filter=vreon.net
        - --provider=aws
        - --registry=txt
        - --txt-owner-id=konishi
