apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apex
- bookstack
- calico
- cert-manager
- external-dns
- harbor
- ingress-nginx
- kube-prometheus
- kubeless
- local-path-provisioner
- loki
- minio
- shlink
