apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- kube-prometheus.yaml
patches:
- add-storage.yaml
resources:
- ingresses.yaml
- grafana-pvc.yaml
images:
- name: grafana/grafana
  newTag: 6.3.2
