apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: kafkahq
namespace: kafka
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
configMapGenerator:
- files:
  - application.yaml
  name: kafkahq-config
