apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- ingress-nginx.yaml
resources:
- leader-election-role.yaml
namespace: private-ingress-nginx
namePrefix: private-
patchesStrategicMerge:
- set-args.yaml
- set-hostport.yaml
