apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/private-nginx-configuration
        - --tcp-services-configmap=$(POD_NAMESPACE)/private-tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/private-udp-services
        - --annotations-prefix=nginx.ingress.kubernetes.io
        - --ingress-class=private
        - --report-node-internal-ip-address
        name: nginx-ingress-controller
