apiVersion: platform.discogs.com/v1
kind: HTTPGenerator
metadata:
  name: calico
resources:
- url: https://docs.projectcalico.org/manifests/calico.yaml
  integrity: sha384-5u/W3tiImRq7Lb6P4cOsODRK6xfhUoyEfY3yG+mSbQcyxdzNNMGBMf3I/6cqLEK/
