apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        envFrom:
        - secretRef:
            name: external-dns-aws
            optional: false
