apiVersion: platform.discogs.com/v1
kind: HTTPGenerator
metadata:
  name: kubeless
resources:
- url: https://github.com/kubeless/kubeless/releases/download/v1.0.6/kubeless-v1.0.6.yaml
  integrity: sha384-Zg0hT46g964S/daKY9yCaKIAzFr8A6QVlU2T49LSjbH2akx+/x/4E+pfzzYBYxks
