apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/public-nginx-configuration
        - --tcp-services-configmap=$(POD_NAMESPACE)/public-tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/public-udp-services
        - --annotations-prefix=nginx.ingress.kubernetes.io
        - --ingress-class=public
        - --publish-status-address=152.44.131.234
        name: nginx-ingress-controller
